[project]
name = "fragrancetrack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "curl-cffi>=0.13.0",
    "fastexcel>=0.18.0",
    "polars>=1.35.2",
    "requests>=2.32.5",
]
